# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 22:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 9, 22, 39, 51, 782432, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
