# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170209_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
